#アセンブラアプリ用Makefile
#アプリ設定
APP      = crack2
STACK    = 1k
MALLOC   = 0k

include ../app_make.txt

clean :
	-$(DEL) *.lst
	-$(DEL) *.obj
	-$(DEL) *.map
	-$(DEL) *.bim
	-$(DEL) *.gas
	-$(DEL) chnos.img
