#C言語アプリ用Makefile
#アプリ設定
APP      = winhelo2
STACK    = 8k
MALLOC   = 0k

include ../app_make.txt

clean :
	-$(DEL) *.lst
	-$(DEL) *.obj
	-$(DEL) *.map
	-$(DEL) *.bim
	-$(DEL) *.ca
	-$(DEL) $(APP).nas
	-$(DEL) *.gas
	-$(DEL) chnos.img
